[package]
name = "pairing_ce"

# Remember to change version string in README.md.
version = "0.21.1"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
    "Alex Vlasov <alex.m.vlasov@gmail.com>",
    "Alex Gluchowski <alex@gluchowski.net>"
]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/matter-labs/pairing"
repository = "https://github.com/matter-labs/pairing"
edition = "2018"

[dependencies]
rand = "0.4"
byteorder = "1"
ff = {package = "ff_ce", version = "0.10.*", features = ["derive"]}
# ff = { path = '../ff', package = "ff_ce", features = ["derive"]}
# ff = {package = "ff_ce", git = "https://github.com/matter-labs/ff.git", branch = "playground", features = ["derive"]}

[features]
default = []
