[package]
name = "pairing"
version = "0.10.2"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/ebfull/pairing"
repository = "https://github.com/ebfull/pairing"

[dependencies]
rand = "0.3"
byteorder = "1.1.0"
clippy = { version = "0.0.147", optional = true }

[features]
unstable-wnaf = []
unstable-features = ["unstable-wnaf"]
